version: "3.1"
language: "en"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy

pipeline:
  - name: WhitespaceTokenizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
  - name: EntitySynonymMapper
  - name: ResponseSelector

assistant_id: 20240702-100403-fat-caribou
